### ISSUE TITLE
we will be able to up/downloading txt files of my decks?

### ISSUE THREAD

**Issue by spuzz2019** [PrestonStahley/swccgdb#2]
hey mate...love your site..i only wish more people were posting decks.
i have the following issues..
1. when ever i try and download a text file of my deck, i am getting an error, are you able to fix this?
2. will we be able to upload decks?

cheers Brett

**Comment by PrestonStahley** [comment]
Thanks Brett,

1. Text file download should be fixed.
2. No plans to add new features atm, but pull requests are welcome.
