### ISSUE TITLE
Can you contact me concerning maintainership of swccgdb ?

### ISSUE THREAD

**Issue by psoetens** [PrestonStahley/swccgdb#3]
Hi Preston, I have no means to contact you other than this bug report right now.  The SWCCG Players Committee would like to take over the maintenance of the swccgdb software and website. We noticed the site you're running live on swccgdb.com is running a different/newer version than master on github. Could you please push your latest changes ? You can DM me on https://twitter.com/PeterSoetens or you can email me on my gmail.com email address. Thanks a lot!

**Comment by PrestonStahley** [comment]
Hey, Peter. I've talked with the Players Commitee in the SWCCG Slack, and I believe they are still working on their own fork of this codebase. You're right that there were a few live unfinished features that I hadn't committed to master yet. I will push those shortly.

Closing this issue, let's discuss in the SWCCG Slack.
