### ISSUE TITLE
issue with pictures of the card

### ISSUE THREAD

**Issue by Nathadan** [PrestonStahley/swccgdb#4]
Hi guy ! I really like your sites but I think there is a bug in the loading of pictures of the cards. I'm on Android Phone and sometimes (not always), the picture of the card isn't loaded in the detail page of the card. I only see the little .gif that means the image could not be loaded. Could you please correct this issue cause it's annoying not seeing the card ?
Thanks in advance ! Great job !

**Comment by kfriedli** [comment]
Intermittently, I experience the same issue while using Chrome on Windows 10. Card images do not load. I am not sure what exact steps lead to the issue.

**Comment by Nathadan** [comment]
I have the problem on Chrome on windows 7 on my computer now... There is no image that is loading... Is someone who can correct this reading this issue here ? Or is there no support on the site ? I assume this problem would be easy to fix. Thanks for answering !

**Comment by PrestonStahley** [comment]
Hey @Nathadan,

The card images are hosted by [Scomp Link Access](https://scomp.starwarsccg.org/), which recently moved to a new subdomain.

The urls are now fixed, although you may need to clear your browser cache to see the update.

**Comment by Nathadan** [comment]
Hi Preston ! Thanks for correcting the issue, it seems to work now :) ! I'm glad cause I use your site a lot ! Thanks again man !
